services:
  ttg-server:
    container_name: ttg-server
    build: .
    depends_on:
      - postgres
      - minio
    ports:
      - 8080:8080
    env_file:
      - .env.docker-compose
    init: true

  postgres:
    container_name: ttg-postgres
    image: postgres:17.2-alpine3.21
    ports:
      - 5432:5432
    env_file:
      - .env.docker-compose
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: ttg-pgadmin
    image: dpage/pgadmin4:8.14
    ports:
      - 5050:80
    env_file:
      - .env.docker-compose
    init: true
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    container_name: ttg-minio
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      # The minio API endpoint
      - "9000:9000"
      # The minio web console endpoint
      - "9001:9001"
    env_file:
      - .env.docker-compose
    init: true
    volumes:
      - minio_data:/data

volumes:
  pgadmin_data:
  postgres_data:
  minio_data:
