name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Prettier Check & ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/iron]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install node dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npm run lint

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/iron]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies and run tests
        run: npm install-ci-test

  # Lint our Dockerfile using Hadolint
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/hadolint-action
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  docker-build:
    name: Build Docker image
    # Don't bother running this job unless the other three all pass
    needs: [lint, dockerfile-lint, unit-tests]
    runs-on: ubuntu-latest
    steps:
      # Set up buildx for optimal Docker Builds, see:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build and export
        env:
          # Define an Environment Variable with our Docker Hub Repo
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ttg-server
          # Define one for our GCHR Repo
          GHCR_REPO: ghcr.io/${{ github.repository_owner }}/ttg-server
          # Define an Environment Variable with the current git commit's sha
          # Use the `github` context to get this, see:
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }},${{ env.DOCKERHUB_REPO }}:main,${{ env.GHCR_REPO }}:latest,${{ env.GHCR_REPO }}:${{ env.SHA_TAG }},${{ env.GHCR_REPO }}:main
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar

  docker-hub:
    name: Push image to Docker Hub
    needs: [docker-build]
    # Push only on commits to main i.e. don't push on pull requests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load image
        run: |
          docker load --input /tmp/image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ttg-server
          SHA_TAG: sha-${{ github.sha }}
        run: |
          docker push ${{ env.DOCKERHUB_REPO }}:latest
          docker push ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}
          docker push ${{ env.DOCKERHUB_REPO }}:main

  ghcr:
    name: Push image to GitHub Container Registry
    needs: [docker-build]
    # Push only on commits to main i.e. don't push on pull requests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load image
        run: |
          docker load --input /tmp/image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        env:
          GHCR_REPO: ghcr.io/${{ github.repository_owner }}/ttg-server
          SHA_TAG: sha-${{ github.sha }}
        run: |
          docker push ${{ env.GHCR_REPO }}:latest
          docker push ${{ env.GHCR_REPO }}:${{ env.SHA_TAG }}
          docker push ${{ env.GHCR_REPO }}:main
